kind: Deployment
apiVersion: apps/v1
metadata:
  name: ruby27-diss
  namespace: diss
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruby27-diss
  template:
    metadata:
      labels:
        app: ruby27-diss
    spec:
      containers:
        - name: ruby27-diss
          image: jonnyman9/ruby27-diss-service@sha256:a845d65e09959d6fe358a361d61d89d0aa4bab1e5fe6790dfe227f9373aecda0
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
