kind: Service
apiVersion: v1
metadata:
  name: ruby27-diss
  namespace: diss
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: ruby27-diss
  type: ClusterIP
